# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "revodata-production-terraform"
    dynamodb_table = "tf-revo-lock-table"
    encrypt        = true
    key            = "terraform/revo/terraform.tfstate"
    profile        = "revodata-production"
    region         = "eu-central-1"
  }
}
